<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>SGoSublime: Old syntax file</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.sgo</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.oldsgosublime</string>
	<key>uuid</key>
	<string>f71e23f5-9c93-4854-bcb3-9c0085e2ffae</string>
</dict>
</plist>
